import 'plan_estudio_parvulos.dart';

ItemPlanEstudio _i(String ingles, [String? espanol]) =>
    ItemPlanEstudio(ingles: ingles, espanol: espanol);

CategoriaPlanEstudio _c(String nombre, List<ItemPlanEstudio> items) =>
    CategoriaPlanEstudio(nombre: nombre, items: items);

PeriodoPlanEstudio _p(int numero, List<CategoriaPlanEstudio> categorias) =>
    PeriodoPlanEstudio(numero: numero, categorias: categorias);

final planEstudioPrejardin = <int, PeriodoPlanEstudio>{
  1: _p(1, [
    _c('Commands', [
      _i('Good morning', 'Buenos días'),
      _i('Good afternoon', 'Buenas tardes'),
      _i('Sit down', 'Sentarse'),
      _i('Bye bye', 'Adiós'),
      _i('Hello teacher', 'Hola profesor'),
      _i('Stand up', 'De pie'),
      _i('I have to pee / poop', 'Quiero orinar / hacer popó'),
      _i('See you', 'Hasta luego'),
    ]),
    _c('Dialogue', [
      _i('Hello, what is your name?', 'Hola, ¿cuál es tu nombre?'),
      _i('Hello, I am _____.', 'Hola, soy _____.'),
    ]),
    _c('Vocabulary', [
      _i('My body', 'Mi cuerpo'),
      _i('Who is he?', '¿Quién es él?'),
      _i('Who is she?', '¿Quién es ella?'),
      _i('He is a boy', 'Es un niño'),
      _i('She is a girl', 'Es una niña'),
      _i('Boy', 'Niño'),
      _i('Girl', 'Niña'),
      _i('My hands', 'Mis manos'),
      _i('Where does the hand go?', '¿A dónde va la mano?'),
      _i("It's my right / left hand", 'Es mi mano derecha / izquierda'),
      _i('Right', 'Derecha'),
      _i('Left', 'Izquierda'),
      _i('Colors', 'Colores'),
      _i('What color is it?', '¿Qué color es?'),
      _i("It's blue / red / yellow", 'Es azul / rojo / amarillo'),
      _i('What animal is it?', '¿Qué animal es?'),
      _i("It's a whale", 'Es una ballena'),
      _i('Yellow', 'Amarillo'),
      _i('Blue', 'Azul'),
      _i('Red', 'Rojo'),
      _i('Professions', 'Profesiones'),
      _i('She is a teacher', 'Ella es profesora'),
      _i('He is a policeman', 'Él es policía'),
      _i('He is a doctor', 'Él es doctor'),
      _i('Policeman', 'Policía'),
      _i('Doctor', 'Doctor'),
      _i('Teacher', 'Profesor/a'),
      _i('The family', 'La familia'),
      _i('Dad', 'Papá'),
      _i('Baby', 'Bebé'),
      _i('Cookie', 'Galleta'),
      _i("Baby's bottle", 'Tetero'),
      _i('Yogurt', 'Yogurt'),
      _i('Candy', 'Dulce'),
    ]),
    _c('Songs', [
      _i('Hello dear teacher'),
      _i('Good morning'),
      _i('Left and right'),
    ]),
  ]),
  2: _p(2, [
    _c('Commands', [
      _i('Arms up', 'Brazos arriba'),
      _i('Arms down', 'Brazos abajo'),
      _i('Arms to the front', 'Brazos al frente'),
      _i('Arms to the back', 'Brazos atrás'),
      _i('Arms out', 'Brazos a los lados'),
      _i('Turn around', 'Dar la vuelta'),
      _i('Have you finished?', '¿Terminaste?'),
      _i('Make a line', 'Hagan la fila'),
    ]),
    _c('Dialogue', [
      _i('Hello, how are you?', 'Hola, ¿cómo estás?'),
      _i('I am happy / sad.', 'Estoy feliz / triste.'),
    ]),
    _c('Vocabulary', [
      _i('Emotions', 'Emociones'),
      _i('How do you feel today?', '¿Cómo te sientes hoy?'),
      _i("I'm sad", 'Estoy triste'),
      _i("I'm happy", 'Estoy feliz'),
      _i('Happy', 'Feliz'),
      _i('Sad', 'Triste'),
      _i('The farm', 'La granja'),
      _i('Donkey', 'Burro'),
      _i('Chicken', 'Pollito'),
      _i('Mouse', 'Ratón'),
      _i('Cow', 'Vaca'),
      _i('Cat', 'Gato'),
      _i('Sheep', 'Oveja'),
      _i('Dog', 'Perro'),
      _i('Horse', 'Caballo'),
      _i('Pig', 'Cerdo'),
      _i('Face', 'Cara'),
      _i('Nose', 'Nariz'),
      _i('Mouth', 'Boca'),
      _i('Eyes', 'Ojos'),
      _i('Ears', 'Orejas'),
      _i('Opposites', 'Opuestos'),
      _i('Long', 'Largo'),
      _i('Short', 'Corto'),
      _i('Up', 'Arriba'),
      _i('Down', 'Abajo'),
      _i('Big', 'Grande'),
      _i('Small', 'Pequeño'),
    ]),
    _c('Songs', [_i('Baa baa black sheep'), _i('One little finger')]),
  ]),
  3: _p(3, [
    _c('Commands', [
      _i('Good work', 'Buen trabajo'),
      _i('Clean the classroom', 'Limpien el salón'),
      _i('God bless you', 'Dios te bendiga'),
      _i('Go to the yard', 'Ve al patio'),
      _i('Pick up the papers', 'Recoge los papeles'),
      _i('Tie up the shoes', 'Amárrate los zapatos'),
      _i('Wash your hands', 'Lávate las manos'),
      _i('Point to your eyes', 'Señala tus ojos'),
    ]),
    _c('Dialogue', [
      _i(
        'Do you have a big car / bicycle / television?',
        '¿Tienes un carro / bicicleta / televisor grande?',
      ),
      _i("Yes, I do. / No, I don't.", 'Sí, tengo. / No, no tengo.'),
    ]),
    _c('Vocabulary', [
      _i('Geometric figures', 'Figuras geométricas'),
      _i('Triangle', 'Triángulo'),
      _i('Square', 'Cuadrado'),
      _i('Circle', 'Círculo'),
      _i('Communication', 'Comunicaciones'),
      _i('Radio', 'Radio'),
      _i('Television', 'Televisor'),
      _i('Cellphone', 'Celular'),
      _i('Telephone', 'Teléfono'),
      _i('Transportation', 'Transporte'),
      _i('Bicycle', 'Bicicleta'),
      _i('Airplane', 'Avión'),
      _i('Car', 'Carro'),
      _i('Train', 'Tren'),
      _i('Motorcycle', 'Motocicleta'),
      _i('Ship', 'Barco'),
    ]),
    _c('Songs', [_i('Vocabulary song'), _i('The colors')]),
  ]),
  4: _p(4, [
    _c('Commands', [
      _i('Take care', 'Cuídate'),
      _i('Come here', 'Ven aquí'),
      _i('Pay attention to me', 'Préstame atención'),
      _i('I am hungry', 'Tengo hambre'),
      _i('I am thirsty', 'Tengo sed'),
      _i('Clap your hands', 'Aplaude'),
      _i('Look at the teacher', 'Mira al profesor'),
      _i('Listen to me', 'Escúchame'),
    ]),
    _c('Dialogue', [
      _i('Do you like fruits?', '¿Te gustan las frutas?'),
      _i(
        'Yes, I like ____. / No, I dislike ____.',
        'Sí, me gusta ____. / No, no me gusta ____.',
      ),
    ]),
    _c('Vocabulary', [
      _i('Fruits', 'Frutas'),
      _i('Banana', 'Banano'),
      _i('Strawberry', 'Fresa'),
      _i('Lemon', 'Limón'),
      _i('Apple', 'Manzana'),
      _i('Pineapple', 'Piña'),
      _i('Pear', 'Pera'),
      _i('Orange', 'Naranja'),
      _i('Grapes', 'Uvas'),
      _i('Numbers', 'Números'),
      _i('Zero', 'Cero'),
      _i('One', 'Uno'),
      _i('Two', 'Dos'),
      _i('Three', 'Tres'),
      _i('Four', 'Cuatro'),
      _i('Five', 'Cinco'),
      _i('Six', 'Seis'),
      _i('Seven', 'Siete'),
      _i('Eight', 'Ocho'),
      _i('Nine', 'Nueve'),
      _i('Ten', 'Diez'),
      _i('Patriotic symbols', 'Símbolos patrios'),
      _i('Shield', 'Escudo'),
      _i('Flag', 'Bandera'),
    ]),
    _c('Songs', [_i('Are you sleeping')]),
  ]),
};

final planEstudioJardin = <int, PeriodoPlanEstudio>{
  1: _p(1, [
    _c('Commands', [
      _i('Good morning / good afternoon', 'Buenos días / buenas tardes'),
      _i('Sit down', 'Sentarse'),
      _i('Bye bye', 'Adiós'),
      _i('Stand up', 'De pie'),
      _i('Have you finished?', '¿Terminaste?'),
      _i('Arms up', 'Brazos arriba'),
      _i('Arms down', 'Brazos abajo'),
      _i('Arms to the front', 'Brazos al frente'),
      _i('Arms to the back', 'Brazos atrás'),
      _i('Make a line', 'Hagan la fila'),
      _i('Turn around', 'Dar la vuelta'),
      _i('Go to the principal', 'Ve donde el director'),
    ]),
    _c('Dialogue', [
      _i(
        "Hello, my name is Lina. What's your name?",
        'Hola, mi nombre es Lina. ¿Cuál es tu nombre?',
      ),
      _i('Hello, my name is _____.', 'Hola, mi nombre es _____.'),
    ]),
    _c('Vocabulary', [
      _i('The family', 'La familia'),
      _i('Dad', 'Papá'),
      _i('Mom', 'Mamá'),
      _i('Brother', 'Hermano'),
      _i('Sister', 'Hermana'),
      _i('Baby', 'Bebé'),
      _i('Colors', 'Colores'),
      _i('Yellow', 'Amarillo'),
      _i('Blue', 'Azul'),
      _i('Red', 'Rojo'),
      _i('Brown', 'Café'),
      _i('White', 'Blanco'),
      _i('Orange', 'Anaranjado'),
      _i('Pink', 'Rosado'),
      _i('Gray', 'Gris'),
      _i('Black', 'Negro'),
      _i('Green', 'Verde'),
      _i('Purple', 'Morado'),
      _i('Vowels: A, E, I, O, U', 'Vocales: A, E, I, O, U'),
      _i('Numbers: one to ten', 'Números: uno al diez'),
    ]),
    _c('Songs', [
      _i('Hello dear teacher'),
      _i('Good morning'),
      _i('Hello song'),
      _i('Rain rain go away'),
    ]),
  ]),
  2: _p(2, [
    _c('Commands', [
      _i('Clean the classroom', 'Limpien el salón'),
      _i('Good work', 'Buen trabajo'),
      _i('May I go to the bathroom?', '¿Puedo ir al baño?'),
      _i('God bless you', 'Dios te bendiga'),
      _i('Pick up the papers', 'Recoja los papeles'),
      _i('Come into the classroom', 'Entra al salón'),
      _i('Come here', 'Ven aquí'),
      _i('Pay attention to me', 'Presta atención'),
      _i('I am hungry', 'Tengo hambre'),
      _i('I am thirsty', 'Tengo sed'),
      _i('Look at me', 'Mírenme'),
      _i('Listen to me', 'Escúcheme'),
    ]),
    _c('Dialogue', [
      _i(
        'Hi Lina, I am happy. How are you today?',
        'Hola Lina, estoy feliz. ¿Cómo estás hoy?',
      ),
      _i(
        'Hello Lili, I am happy / sad too.',
        'Hola Lili, también estoy feliz / triste.',
      ),
    ]),
    _c('Vocabulary', [
      _i('Sea animals', 'Animales del océano'),
      _i('Dolphin', 'Delfín'),
      _i('Shark', 'Tiburón'),
      _i('Seal', 'Foca'),
      _i('Octopus', 'Pulpo'),
      _i('Whale', 'Ballena'),
      _i('Fish', 'Pescado'),
      _i('Fruits and vegetables', 'Frutas y vegetales'),
      _i('Pear', 'Pera'),
      _i('Orange', 'Naranja'),
      _i('Tomato', 'Tomate'),
      _i('Apple', 'Manzana'),
      _i('Banana', 'Banano'),
      _i('Grapes', 'Uvas'),
      _i('Watermelon', 'Sandía'),
      _i('Carrot', 'Zanahoria'),
      _i('Onion', 'Cebolla'),
      _i('Celery', 'Apio'),
      _i('Lettuce', 'Lechuga'),
      _i('Cucumber', 'Pepino'),
      _i('My food', 'Mi comida'),
      _i('Milk', 'Leche'),
      _i('Ice cream', 'Helado'),
      _i('Cake', 'Torta'),
      _i('Meat', 'Carne'),
      _i('Chicken', 'Pollo'),
      _i('Soup', 'Sopa'),
      _i('Eggs', 'Huevos'),
    ]),
    _c('Songs', [
      _i('Happy fruits'),
      _i('Rice pudding'),
      _i('This is the way'),
    ]),
  ]),
  3: _p(3, [
    _c('Commands', [
      _i('Be careful', 'Ve con cuidado'),
      _i('Tie up the shoes', 'Amárrate los zapatos'),
      _i('Look at the teacher', 'Mira al profesor'),
      _i('Good work', 'Buen trabajo'),
      _i("Don't forget", 'No olvides'),
      _i("It's time to go home", 'Hora de ir a casa'),
      _i(
        'Let me have your book / ruler / pen',
        'Permíteme tu libro / regla / esfero',
      ),
      _i('Point to your eyes / nose', 'Señala tus ojos / nariz'),
      _i('Repeat slowly', 'Repite despacio'),
      _i('I want some water, please', 'Quiero agua, por favor'),
      _i('Close the door / window', 'Cierra la puerta / ventana'),
      _i('Open the door / window', 'Abre la puerta / ventana'),
    ]),
    _c('Dialogue', [
      _i(
        'Do you have a small / big pencil / book?',
        '¿Tienes un lápiz / libro pequeño / grande?',
      ),
      _i(
        'Yes, I have a big / small _____.',
        'Sí, tengo un _____ grande / pequeño.',
      ),
    ]),
    _c('Vocabulary', [
      _i('Numbers: eleven to twenty', 'Números: once al veinte'),
      _i('My garden', 'Mi jardín'),
      _i('Swing', 'Columpio'),
      _i('Bucket', 'Cubeta'),
      _i('Shovel', 'Pala'),
      _i('Slide', 'Resbalador'),
      _i('Toy', 'Juguete'),
      _i('My classroom', 'Mi salón'),
      _i('Book', 'Libro'),
      _i('Chair', 'Silla'),
      _i('Scissors', 'Tijeras'),
      _i('Crayon', 'Crayola'),
      _i('Desk', 'Pupitre'),
      _i('Pencil', 'Lápiz'),
      _i('Lunch box', 'Lonchera'),
      _i('Pencil case', 'Cartuchera'),
      _i('Thermos', 'Termo'),
      _i('Eraser', 'Borrador'),
      _i('Board', 'Tablero'),
      _i('Bag', 'Maleta'),
      _i('Opposites', 'Opuestos'),
      _i('A lot', 'Muchos'),
      _i('A little', 'Pocos'),
      _i('Fat', 'Gordo'),
      _i('Thin', 'Delgado'),
    ]),
    _c('Songs', [
      _i('Walking in the jungle'),
      _i("If you're happy"),
      _i('Simple song'),
    ]),
  ]),
  4: _p(4, [
    _c('Commands', [
      _i('Have a good day', 'Que tengas un buen día'),
      _i('The school bus arrived', 'Llegó el recorrido'),
      _i('Well done / very good', 'Bien hecho / muy bien'),
      _i('Take the English book', 'Toma el libro de inglés'),
      _i('Take care', 'Cuídate'),
      _i('He / she is intelligent', 'Él / ella es inteligente'),
      _i('Can you repeat to me, please?', '¿Puedes repetirme, por favor?'),
      _i("It's excellent", 'Es excelente'),
      _i('Put your book in your bag', 'Guarda tu libro en la maleta'),
      _i('Wash your hands', 'Lávate las manos'),
      _i('God bless you', 'Dios te bendiga'),
    ]),
    _c('Dialogue', [
      _i(
        'See you tomorrow. Bye bye, take care and God bless you.',
        'Nos vemos mañana. Adiós, cuídate y que Dios te bendiga.',
      ),
      _i(
        'God bless you too, be careful.',
        'Que Dios te bendiga también, ten cuidado.',
      ),
      _i('Thanks, teacher. See you.', 'Gracias, profe. Nos vemos.'),
    ]),
    _c('Vocabulary', [
      _i('Clothes', 'Prendas de vestir'),
      _i('Shirt', 'Camisa'),
      _i('Socks', 'Medias'),
      _i('Skirt', 'Falda'),
      _i('Cap', 'Cachucha'),
      _i('Shoes', 'Zapatos'),
      _i('Tie', 'Corbata'),
      _i('Pants', 'Pantalones'),
      _i('Sweater', 'Suéter'),
      _i('Dress', 'Vestido'),
      _i('Boots', 'Botas'),
      _i('T-shirt', 'Camiseta'),
      _i('My body', 'Mi cuerpo'),
      _i('Boy', 'Niño'),
      _i('Girl', 'Niña'),
      _i('Legs', 'Piernas'),
      _i('Knees', 'Rodillas'),
      _i('Shoulders', 'Hombros'),
      _i('Feet', 'Pies'),
      _i('Foot', 'Pie'),
      _i('Head', 'Cabeza'),
      _i('Eyes', 'Ojos'),
      _i('Ears', 'Orejas'),
      _i('Nose', 'Nariz'),
      _i('Mouth', 'Boca'),
      _i('Neck', 'Cuello'),
      _i('Professions', 'Profesiones'),
      _i('Nurse', 'Enfermera'),
      _i('Architect', 'Arquitecto'),
      _i('Singer', 'Cantante'),
    ]),
    _c('Songs', [_i('Twinkle twinkle little star'), _i('Point and touch')]),
  ]),
};

final planEstudioTransicion = <int, PeriodoPlanEstudio>{
  1: _p(1, [
    _c('Commands', [
      _i('Good morning / good afternoon', 'Buenos días / buenas tardes'),
      _i('Sit down', 'Sentarse'),
      _i('Bye bye', 'Adiós'),
      _i('Hello teacher', 'Hola profesor'),
      _i('Wash your hands', 'Lávate las manos'),
      _i('Have you finished?', '¿Terminaste?'),
      _i('Arms up', 'Brazos arriba'),
      _i('Arms down', 'Brazos abajo'),
      _i('Arms to the front', 'Brazos al frente'),
      _i('Arms to the back', 'Brazos atrás'),
      _i('Arms out', 'Brazos a los lados'),
      _i('Make a line', 'Hagan la fila'),
      _i('Bring me the marker / pen', 'Tráeme el marcador / esfero'),
      _i('Turn around', 'Dar la vuelta'),
      _i('Come into the classroom', 'Entra al salón'),
    ]),
    _c('Dialogue', [
      _i('Hello, I am Martin.', 'Hola, soy Martin.'),
      _i(
        "Let's practice the commands / songs / vocabulary.",
        'Practiquemos los comandos / canciones / vocabulario.',
      ),
      _i("Let's start.", 'Iniciemos.'),
    ]),
    _c('Vocabulary', [
      _i('My face', 'Mi cara'),
      _i('Head', 'Cabeza'),
      _i('Eyes', 'Ojos'),
      _i('Ears', 'Orejas'),
      _i('Nose', 'Nariz'),
      _i('Mouth', 'Boca'),
      _i('My body', 'Mi cuerpo'),
      _i('Legs', 'Piernas'),
      _i('Knees', 'Rodillas'),
      _i('Shoulders', 'Hombros'),
      _i('Feet', 'Pies'),
      _i('Foot', 'Pie'),
      _i('Toes', 'Dedos'),
      _i('The family', 'La familia'),
      _i('Dad', 'Papá'),
      _i('Mom', 'Mamá'),
      _i('Brother', 'Hermano'),
      _i('Sister', 'Hermana'),
      _i('Baby', 'Bebé'),
      _i('Grandma', 'Abuela'),
      _i('Grandpa', 'Abuelo'),
      _i('Transportation', 'Transportes'),
      _i('Motorcycle', 'Motocicleta'),
      _i('Train', 'Tren'),
      _i('Ship', 'Barco'),
      _i('Car', 'Carro'),
      _i('Bicycle', 'Bicicleta'),
      _i('Airplane', 'Avión'),
      _i('Communication', 'Comunicaciones'),
      _i('Telephone', 'Teléfono'),
      _i('Television', 'Televisión'),
      _i('Computer', 'Computador'),
      _i('Radio', 'Radio'),
      _i(
        'Colors: yellow, blue, red, brown, white, orange, pink, gray, black, green, purple',
        'Colores básicos',
      ),
    ]),
    _c('Songs', [
      _i('Hello dear teacher'),
      _i('Good morning'),
      _i('Hello song'),
      _i('Ten little numbers'),
    ]),
  ]),
  2: _p(2, [
    _c('Commands', [
      _i('Tie up the shoes', 'Amárrate los zapatos'),
      _i('Take care', 'Cuídate'),
      _i('Come here', 'Ven aquí'),
      _i('Pay attention to me', 'Presta atención'),
      _i('I am hungry', 'Tengo hambre'),
      _i('I am thirsty', 'Tengo sed'),
      _i('May I go to the bathroom?', '¿Puedo ir al baño?'),
      _i('Look at me', 'Mírame'),
      _i('Listen to me', 'Escúchame'),
      _i('Go to the principal', 'Ve al director'),
      _i('Put your book in your bag', 'Guarda tu libro en la maleta'),
      _i('Wash your hands', 'Lávate las manos'),
      _i("Don't say bad words", 'No digas malas palabras'),
      _i('Take out the colors', 'Saca los colores'),
      _i('God bless you', 'Dios te bendiga'),
    ]),
    _c('Dialogue', [
      _i("Don't forget your homework.", 'No olvides tu tarea.'),
      _i('I finished. Bye bye and take care.', 'Terminé. Adiós y cuídate.'),
      _i(
        "I haven't finished yet. Don't erase, please.",
        'No he terminado. No borres, por favor.',
      ),
    ]),
    _c('Vocabulary', [
      _i('Numbers: one to twenty', 'Números: uno al veinte'),
      _i('My house', 'Mi casa'),
      _i('Kitchen', 'Cocina'),
      _i('Bathroom', 'Baño'),
      _i('Bedroom', 'Alcoba'),
      _i('Living room', 'Sala'),
      _i('Dining room', 'Comedor'),
      _i('Hairbrush', 'Peine'),
      _i('Toilet', 'Inodoro'),
      _i('Soap', 'Jabón'),
      _i('Toothbrush', 'Cepillo de dientes'),
      _i('Sink', 'Lavamanos'),
      _i('Toothpaste', 'Crema dental'),
      _i('Chair', 'Silla'),
      _i('Curtain', 'Cortina'),
      _i('Table', 'Mesa'),
      _i('Closet', 'Armario'),
      _i('Pillow', 'Almohada'),
      _i('Night table', 'Mesa de noche'),
      _i('Bed', 'Cama'),
      _i('Lamp', 'Lámpara'),
      _i('Slippers', 'Pantuflas'),
      _i('Ball', 'Balón'),
      _i('Carpet', 'Tapete'),
      _i('Window', 'Ventana'),
      _i('My city', 'Mi ciudad'),
      _i('Restaurant', 'Restaurante'),
      _i('Fire station', 'Estación de bomberos'),
      _i('Hospital', 'Hospital'),
      _i('Police station', 'Estación de policía'),
      _i('School', 'Colegio'),
      _i('Church', 'Iglesia'),
      _i('Park', 'Parque'),
      _i('Bus stop', 'Parada de autobús'),
    ]),
    _c('Songs', [_i('Old MacDonald'), _i('My house'), _i('Bingo')]),
  ]),
  3: _p(3, [
    _c('Commands', [
      _i('Put the garbage in the basket', 'Coloca la basura en la cesta'),
      _i('Study for tomorrow', 'Estudia para mañana'),
      _i('See you tomorrow', 'Nos vemos mañana'),
      _i('Calm down', 'Cálmate'),
      _i('Take the English book', 'Toma el libro de inglés'),
      _i("Don't forget", 'No olvides'),
      _i("It's time to go home", 'Hora de ir a casa'),
      _i(
        'Let me have your book / ruler / pen',
        'Permíteme tu libro / regla / esfero',
      ),
      _i('Point to your eyes / nose', 'Señala tus ojos / nariz'),
      _i('Repeat slowly', 'Repite despacio'),
      _i('I want some water, please', 'Quiero agua, por favor'),
      _i('Close the door / window', 'Cierra la puerta / ventana'),
      _i('Open the door / window', 'Abre la puerta / ventana'),
      _i('Can you repeat, please?', '¿Puedes repetir, por favor?'),
      _i('Clean the classroom', 'Limpia el salón'),
    ]),
    _c('Dialogue', [
      _i('What are you wearing today?', '¿Qué llevas puesto hoy?'),
      _i(
        'I am wearing a T-shirt / skirt / pants.',
        'Estoy usando una camiseta / falda / pantalones.',
      ),
      _i(
        'What color is your T-shirt / skirt / pants?',
        '¿De qué color es tu camiseta / falda / pantalones?',
      ),
    ]),
    _c('Vocabulary', [
      _i('Professions', 'Profesiones'),
      _i('Doctor', 'Doctor'),
      _i('Chef', 'Cocinero'),
      _i('Police officer', 'Policía'),
      _i('Priest', 'Padre'),
      _i('Nurse', 'Enfermera'),
      _i('Firefighter', 'Bombero'),
      _i('Teacher', 'Profesor'),
      _i('Alphabet: A to Z', 'Abecedario: A a Z'),
      _i('Clothes', 'Prendas de vestir'),
      _i('Shirt', 'Camisa'),
      _i('Socks', 'Medias'),
      _i('Skirt', 'Falda'),
      _i('Pants', 'Pantalones'),
      _i('Boots', 'Botas'),
      _i('Blouse', 'Blusa'),
      _i('Boxers', 'Pantaloncillos'),
      _i('Shoes', 'Zapatos'),
      _i('Patriotic symbols', 'Símbolos patrios'),
      _i('Flag', 'Bandera'),
      _i('Shield', 'Escudo'),
      _i('Map', 'Mapa'),
      _i('Numbers: twenty-one to fifty', 'Números: veintiuno al cincuenta'),
    ]),
    _c('Songs', [
      _i('Bingo'),
      _i('Walking in the jungle'),
      _i('Put on your shoes'),
      _i('Alphabet song'),
    ]),
  ]),
  4: _p(4, [
    _c('Commands', [
      _i('Can you repeat, please?', '¿Puedes repetir, por favor?'),
      _i('Congratulations for the homework', 'Felicitaciones por tu tarea'),
      _i('Pray at night', 'Ora en la noche'),
      _i('Lend me the book', 'Préstame el libro'),
      _i(
        'Your mother needs you at the door',
        'Tu mamá te necesita en la puerta',
      ),
      _i('See you', 'Hasta luego'),
      _i('Take a break', 'Toma un descanso'),
      _i('Sweet dreams', 'Dulces sueños'),
      _i('I have to pee / poop', 'Quiero ir al baño'),
      _i('Put your things away', 'Guarda tus cosas'),
      _i("That's nice", 'Eso es bueno'),
      _i('Go to the yard / board', 'Ve al patio / tablero'),
      _i('Pick up the papers', 'Recoge los papeles'),
      _i('Very good / well done', 'Muy bien / bien hecho'),
      _i('Are you sick?', '¿Estás enfermo?'),
    ]),
    _c('Dialogue', [
      _i('What is your favorite animal?', '¿Cuál es tu animal favorito?'),
      _i(
        'My favorite animal is the elephant / giraffe.',
        'Mi animal favorito es el elefante / jirafa.',
      ),
      _i(
        'Is the elephant big or small? Is the giraffe tall or short?',
        '¿El elefante es grande o pequeño? ¿La jirafa es alta o baja?',
      ),
      _i(
        'The elephant is big. The giraffe is tall.',
        'El elefante es grande. La jirafa es alta.',
      ),
    ]),
    _c('Vocabulary', [
      _i('Fruits', 'Frutas'),
      _i('Pear', 'Pera'),
      _i('Orange', 'Naranja'),
      _i('Lemon', 'Limón'),
      _i('Apple', 'Manzana'),
      _i('Banana', 'Banano'),
      _i('Grapes', 'Uvas'),
      _i('Watermelon', 'Sandía'),
      _i('Pineapple', 'Piña'),
      _i('Cherry', 'Cereza'),
      _i('Coconut', 'Coco'),
      _i('Mango', 'Mango'),
      _i('Strawberry', 'Fresa'),
      _i('My classroom', 'Mi salón de clase'),
      _i('Chair', 'Silla'),
      _i('Scissors', 'Tijeras'),
      _i('Crayon', 'Crayola'),
      _i('Marker', 'Marcador'),
      _i('Glue', 'Pegamento'),
      _i('Book', 'Libro'),
      _i('Pen', 'Esfero'),
      _i('Table', 'Mesa'),
      _i('Calculator', 'Calculadora'),
      _i('Desk', 'Escritorio'),
      _i('Paintbrush', 'Pincel'),
      _i('Pencil case', 'Cartuchera'),
      _i('Pencil', 'Lápiz'),
      _i('Notebook', 'Cuaderno'),
      _i('Sharpener', 'Sacapuntas'),
      _i('Eraser', 'Borrador'),
      _i('Ruler', 'Regla'),
      _i('Geometric figures', 'Figuras geométricas'),
      _i('Circle', 'Círculo'),
      _i('Rectangle', 'Rectángulo'),
      _i('Triangle', 'Triángulo'),
      _i('Square', 'Cuadrado'),
      _i('Semicircle', 'Semicírculo'),
      _i('Wild animals', 'Animales salvajes'),
      _i('Snake', 'Serpiente'),
      _i('Lion', 'León'),
      _i('Hippopotamus', 'Hipopótamo'),
      _i('Tiger', 'Tigre'),
      _i('Giraffe', 'Jirafa'),
      _i('Crocodile', 'Cocodrilo'),
      _i('Zebra', 'Cebra'),
      _i('Elephant', 'Elefante'),
    ]),
    _c('Songs', [_i('We wish you a Merry Christmas'), _i('What do you have?')]),
  ]),
};

final planesEstudioPorGrado = <String, Map<int, PeriodoPlanEstudio>>{
  'Párvulos': _organizarVocabulario(planEstudioParvulos),
  'Prejardín': _organizarVocabulario(planEstudioPrejardin),
  'Jardín': _organizarVocabulario(planEstudioJardin),
  'Transición': _organizarVocabulario(planEstudioTransicion),
};

const _temasVocabulario = <String>{
  'Colors',
  'My body',
  'My Body',
  'My Face',
  'My face',
  'My hands',
  'My family',
  'The family',
  'Professions',
  'Animals',
  'Wild animals',
  'Wilds animal',
  'Opposites',
  'Opposite',
  'Emotions',
  'The farm',
  'Face',
  'Geometric figures',
  'Geometric figure',
  'Communication',
  'Transportation',
  'Fruits',
  'The fruits',
  'Numbers',
  'Patriotic symbols',
  'Sea animals',
  'Fruits and vegetables',
  'My food',
  'My garden',
  'My Classroom',
  'My classroom',
  'Clothes',
  'My house',
  'Bathroom',
  'Living room',
  'Bedroom',
  'My city',
  'Alphabet',
};

Map<int, PeriodoPlanEstudio> _organizarVocabulario(
  Map<int, PeriodoPlanEstudio> plan,
) => {
  for (final periodo in plan.entries)
    periodo.key: PeriodoPlanEstudio(
      numero: periodo.value.numero,
      categorias: [
        for (final categoria in periodo.value.categorias)
          categoria.nombre == 'Vocabulary'
              ? CategoriaPlanEstudio(
                  nombre: categoria.nombre,
                  items: _agruparItemsVocabulario(categoria.items),
                )
              : categoria,
      ],
    ),
};

List<ItemPlanEstudio> _agruparItemsVocabulario(List<ItemPlanEstudio> items) {
  final resultado = <ItemPlanEstudio>[];
  var tema = 'General vocabulary';
  for (final item in items) {
    if (_temasVocabulario.contains(item.ingles)) {
      tema = item.ingles;
      final guia = _guiaParaTema(tema);
      resultado.addAll([
        ItemPlanEstudio(ingles: guia.$1, tema: tema, soloIngles: true),
        ItemPlanEstudio(ingles: guia.$2, tema: tema, soloIngles: true),
      ]);
      continue;
    }
    resultado.add(
      ItemPlanEstudio(
        ingles: item.ingles,
        pronunciacion: item.pronunciacion,
        espanol: item.espanol,
        tema: tema,
      ),
    );
  }
  return resultado;
}

(String, String) _guiaParaTema(String tema) {
  final normalizado = tema.toLowerCase();
  if (normalizado.contains('color')) {
    return ('What color is it?', "It's _____.");
  }
  if (normalizado.contains('number')) {
    return ('What number is it?', "It's _____.");
  }
  if (normalizado.contains('animal') || normalizado == 'the farm') {
    return ('What animal is it?', "It's a / an _____.");
  }
  if (normalizado.contains('fruit')) {
    return ('What fruit is it?', "It's a / an _____.");
  }
  if (normalizado.contains('family') || normalizado.contains('profession')) {
    return ('Who is he / she?', 'He / She is _____.');
  }
  if (normalizado.contains('emotion')) {
    return ('How do you feel today?', "I'm _____.");
  }
  if (normalizado.contains('opposite')) {
    return ('How is it?', "It's _____.");
  }
  if (normalizado.contains('alphabet')) {
    return ('What letter is it?', "It's _____.");
  }
  return ('What is it?', "It's a / an _____.");
}
